import java.sql.*;
import javax.swing.JOptionPane;
 

/**
 *
 * @author Admin
 */
public class registrationform extends javax.swing.JFrame {

    /**
     * Creates new form registrationform
     */void reset()
     { tname.setText(""); 
       troom.setText("");
       tocc.setText("");
       tadd.setText("");
       tadh.setText("");
       tphone.setText("");
       tgname.setText("");
       tdob.setText("");
       tdoa.setText(""); 
     }

    public registrationform() {
        initComponents();
         setSize(710, 540);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tname = new javax.swing.JTextField();
        tphone = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        tdob = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        tgname = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tadd = new javax.swing.JTextArea();
        jLabel8 = new javax.swing.JLabel();
        tdoa = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        tocc = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        tadh = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        troom = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("REGISTRATION FORM");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(220, 10, 280, 28);

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 51));
        jLabel2.setText("Full Name               :");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(10, 100, 130, 26);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(31, 79, 0, 0);

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 51));
        jLabel4.setText("  Phone No               :");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(0, 150, 140, 26);

        tname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tnameActionPerformed(evt);
            }
        });
        getContentPane().add(tname);
        tname.setBounds(140, 100, 400, 30);

        tphone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tphoneActionPerformed(evt);
            }
        });
        getContentPane().add(tphone);
        tphone.setBounds(140, 150, 150, 30);

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 51));
        jLabel5.setText(" DOB :");
        getContentPane().add(jLabel5);
        jLabel5.setBounds(360, 150, 52, 26);

        tdob.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdobActionPerformed(evt);
            }
        });
        getContentPane().add(tdob);
        tdob.setBounds(410, 150, 127, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 51));
        jLabel6.setText("Guardian  Name      :");
        getContentPane().add(jLabel6);
        jLabel6.setBounds(10, 200, 130, 26);

        tgname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tgnameActionPerformed(evt);
            }
        });
        getContentPane().add(tgname);
        tgname.setBounds(140, 200, 400, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 51));
        jLabel7.setText("Permanent Address  :");
        getContentPane().add(jLabel7);
        jLabel7.setBounds(0, 250, 140, 26);

        tadd.setColumns(20);
        tadd.setRows(5);
        jScrollPane1.setViewportView(tadd);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(140, 240, 400, 40);

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 51));
        jLabel8.setText("Date Of Admission   :");
        getContentPane().add(jLabel8);
        jLabel8.setBounds(0, 300, 130, 26);

        tdoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tdoaActionPerformed(evt);
            }
        });
        getContentPane().add(tdoa);
        tdoa.setBounds(140, 300, 150, 30);

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 51));
        jLabel9.setText("Occupation :");
        getContentPane().add(jLabel9);
        jLabel9.setBounds(330, 350, 79, 26);

        tocc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                toccActionPerformed(evt);
            }
        });
        getContentPane().add(tocc);
        tocc.setBounds(410, 350, 127, 30);

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 51));
        jLabel10.setText(" Aadhar Number    :");
        getContentPane().add(jLabel10);
        jLabel10.setBounds(10, 350, 130, 26);

        tadh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tadhActionPerformed(evt);
            }
        });
        getContentPane().add(tadh);
        tadh.setBounds(140, 350, 152, 30);

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 51));
        jLabel11.setText("Room No                :");
        getContentPane().add(jLabel11);
        jLabel11.setBounds(10, 60, 130, 26);

        troom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                troomActionPerformed(evt);
            }
        });
        getContentPane().add(troom);
        troom.setBounds(140, 60, 150, 30);

        jButton1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton1.setText("Save");
        jButton1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(70, 430, 70, 30);

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton2.setText("Reset");
        jButton2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(310, 430, 70, 30);

        jButton3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton3.setText("Back");
        jButton3.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(550, 430, 65, 30);

        jButton5.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jButton5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Icons\\home-icon (1).png")); // NOI18N
        jButton5.setText("Home");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5);
        jButton5.setBounds(580, 20, 100, 30);

        jLabel13.setIcon(new javax.swing.ImageIcon("C:\\Users\\Admin\\Pictures\\Icons\\sk2.jpg")); // NOI18N
        jLabel13.setText("jLabel13");
        getContentPane().add(jLabel13);
        jLabel13.setBounds(0, -10, 720, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tdobActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdobActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdobActionPerformed

    private void tphoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tphoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tphoneActionPerformed

    private void tgnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tgnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tgnameActionPerformed

    private void tdoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tdoaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tdoaActionPerformed

    private void toccActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_toccActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_toccActionPerformed

    private void tadhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tadhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tadhActionPerformed

    private void troomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_troomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_troomActionPerformed

    private void tnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
           
       try{
            Class.forName("com.mysql.jdbc.Driver");
            Connection c = DriverManager.getConnection("jdbc:mysql://localhost:3306/project","root","root");
            PreparedStatement ps=c.prepareStatement("insert into details(Name, Phone_No, DOB, Guardian, Permanent_Address, Date_Of_Admission ,Occupation ,Aadhar_No, Room_No) values('"+tname.getText()+"',"+Integer.parseInt(tphone.getText())+",'"+tdob.getText()+"','"+tgname.getText()+"','"+tadd.getText()+"','"+tdoa.getText()+"','"+tocc.getText()+"',"+Integer.parseInt(tadh.getText())+","+Integer.parseInt(troom.getText())+")");
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog(null,"Registration completed successfullly");
            
           home h=new home();
            h.setVisible(true);
            dispose();
            
            PreparedStatement p= c.prepareStatement("update beds set Vacant_beds=Vacant_beds-1, Occupied_beds=Occupied_beds+1 where Room_No="+Integer.parseInt(troom.getText())+"");
            p.executeUpdate();
       
       }   
       catch(Exception e){

       }
            
            
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       reset(); 
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
       newadmission n=new newadmission();
       n.setVisible(true);
       dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        home h=new home();
        h.setVisible(true);
        dispose();
    }//GEN-LAST:event_jButton5ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(registrationform.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new registrationform().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea tadd;
    private javax.swing.JTextField tadh;
    private javax.swing.JTextField tdoa;
    private javax.swing.JTextField tdob;
    private javax.swing.JTextField tgname;
    private javax.swing.JTextField tname;
    private javax.swing.JTextField tocc;
    private javax.swing.JTextField tphone;
    private javax.swing.JTextField troom;
    // End of variables declaration//GEN-END:variables
}
